name: HeistMC
main: anti.projects.heistmc.HeistMC
version: 1.3.5
author: AntiWarIsaac
api-version: 1.16
commands:
  join:
    description: "Join a Heist lobby"
    usage: "Usage: /join"

  leave:
    description: "Leave a Heist"
    usage: "Usage: /leave"

  dbg:
    description: "For debugging only. Used to break out of the game flow etc."
    usage: "Usage: /dbg <command>"

  build:
    description: "Create a HeistMC map."
    usage: "Usage: /build"

  export:
    description: "Export a HeistMC map."
    usage: "Usage: /export <map name...>"

  export-lobby:
    description: "Export a HeistMC map as the map to be used for waiting lobbies."
    usage: "Usage: /export-lobby"

  money:
    description: "Manipulate your money for development testing."
    usage: "Usage: /money <amount>"

  set-developer:
    description: "Give a user developer permissions"
    usage: "Usage: /set-developer <username>"

  revoke-developer:
    description: "Revoke developer permissions from a user."
    usage: "Usage: /revoke-developer <username>"

  set-builder:
    description: "Give a user builder permissions"
    usage: "Usage: /set-builder <username>"

  revoke-builder:
    description: "Revoke builder permissions from a user."
    usage: "Usage: /revoke-builder <username>"
